// Re-export all coin metadata for easy access
export {
  DEEP_METADATA,
  SUI_METADATA,
  DBUSDC_METADATA,
  DBUSDT_METADATA,
  WAL_METADATA,
  DBTC_METADATA,
} from "./coins";

// Convenience map for token lookups
import {
  DEEP_METADATA,
  SUI_METADATA,
  DBUSDC_METADATA,
  DBUSDT_METADATA,
  WAL_METADATA,
  DBTC_METADATA,
} from "./coins";

export const SUPPORTED_TOKENS = {
  DEEP: DEEP_METADATA,
  SUI: SUI_METADATA,
  DBUSDC: DBUSDC_METADATA,
  DBUSDT: DBUSDT_METADATA,
  WAL: WAL_METADATA,
  DBTC: DBTC_METADATA,
} as const;

export const TOKEN_BY_TYPE = {
  [DEEP_METADATA.type]: DEEP_METADATA,
  [SUI_METADATA.type]: SUI_METADATA,
  [DBUSDC_METADATA.type]: DBUSDC_METADATA,
  [DBUSDT_METADATA.type]: DBUSDT_METADATA,
  [WAL_METADATA.type]: WAL_METADATA,
  [DBTC_METADATA.type]: DBTC_METADATA,
} as const;

export const TOKEN_BY_ID = {
  [DEEP_METADATA.id]: DEEP_METADATA,
  [SUI_METADATA.id]: SUI_METADATA,
  [DBUSDC_METADATA.id]: DBUSDC_METADATA,
  [DBUSDT_METADATA.id]: DBUSDT_METADATA,
  [WAL_METADATA.id]: WAL_METADATA,
  [DBTC_METADATA.id]: DBTC_METADATA,
} as const;
